version: "3.9"  # optional since v1.27.0
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
  app:
    image: jmix-pm:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: dev
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jmixpmdev